---
deployment:
    tasks:
        - export DEPLOYPATH=/home/ussander/opencart/
        - /bin/cp -R upload/. $DEPLOYPATH
        - /bin/cp install.xml "$DEPLOYPATH"system/opencart-category-related.ocmod.xml
